Update ViewConfig#display_label for consistency with similar methods
projectblacklight/blacklight pull request #2431
Opened 2021-03-05 19:13 UTC by cbeer

2021-03-06 20:21 UTC, jcoyne requested changes

2021-03-06 20:21 UTC, jcoyne commented on lib/blacklight/configuration/view_config.rb
> +      Deprecation.warn('Passing the key argument to ViewConfig#display_label is deprecated')
Does this need a conditional?

2021-03-06 20:56 UTC, cbeer commented on lib/blacklight/configuration/view_config.rb
> +      Deprecation.warn('Passing the key argument to ViewConfig#display_label is deprecated')
```suggestion
      Deprecation.warn('Passing the key argument to ViewConfig#display_label is deprecated') if deprecated_key.present?
```

2021-03-07 03:25 UTC, jcoyne approved these changes

2021-03-10 15:23 UTC, merged