Work around an upstream view_component bug with inherited by ensuring compile is called at runtime
projectblacklight/blacklight pull request #2679
Opened 2022-03-24 15:46 UTC by cbeer

See https://github.com/github/view_component/issues/1315.

I think extracting our own base component is generally useful (e.g. #2664)

2022-03-24 18:23 UTC, jcoyne approved these changes

2022-03-25 16:29 UTC, jcoyne commented
It looks like there's an upstream fix for this: https://github.com/github/view_component/pull/1317  Should we wait it out?

2022-03-28 15:19 UTC, jcoyne commented
The fix is released now: https://github.com/github/view_component/blob/main/docs/CHANGELOG.md#2520

2022-04-13 16:17 UTC, jcoyne requested changes

2022-04-13 16:17 UTC, jcoyne commented on lib/blacklight/component.rb
> +    def render_in(view_context, &block)
Can you remove this?

2022-04-20 18:46 UTC, cbeer commented on lib/blacklight/component.rb
> +    def render_in(view_context, &block)
Done

2022-04-20 20:55 UTC, jcoyne approved these changes

2022-04-20 20:55 UTC, merged