View component tools support
projectblacklight/blacklight pull request #3106
Opened 2023-11-09 21:19 UTC by body-clock

Addresses #3102 

ViewComponent 3.0.0 switched the Slots API and how they're called. This PR addresses some code that had not been updated to reflect those changes. It also aims to test that the Tools components render their modals properly to prevent similar issues in the future.

Just one note - because the citation tool relies on methods not present in core Blacklight, the tool's functionality cannot test that the modal content renders correctly. I've chosen to just test that the header renders correctly. Through my investigation, I've also noticed that the [Blacklight Demo](https://demo.projectblacklight.org/catalog/2009002583) doesn't have a working citation tool - something to think about.

2023-12-27 16:47 UTC, jcoyne commented
Will this still work with view_component 2?  The gemspec indicates that 2 is an acceptable version.

2023-12-27 16:50 UTC, jcoyne requested changes

2023-12-27 16:50 UTC, jcoyne commented on spec/features/tools_spec.rb
> +    click_link 'Email'
Isn't this a duplicate case as the `spec/features/modal_spec.rb`?

2024-01-04 18:43 UTC, body-clock commented
> Will this still work with view_component 2? The gemspec indicates that 2 is an acceptable version.

I'm having a hard time figuring this out. The ViewComponent changelog for 3.0 lists this as a breaking change, but it seems this convention has been adopted throughout the rest of the Blacklight gem. For example `app/views/catalog/facet.html.erb` uses `component.with_prefix`, `component.with_title`, and `component.with_footer`, following the conventions of VC 3.

2024-01-17 22:03 UTC, jrochkind commented
> Will this still work with view_component 2? The gemspec indicates that 2 is an acceptable version.

@jcoyne , the gemspec requires at least view_component 2.66, not actually any 2. 

The "newer" `with_` API is available from 2.54.0 on. https://viewcomponent.org/CHANGELOG.html#2540

So should be good!

2024-01-18 01:18 UTC, jcoyne commented
Thank you for taking the lead on this @body-clock.  I think I've incorporated all this into #3120 and merged into main.

2024-01-18 01:18 UTC, closed without merging