Bump max Rails version to 7.2
projectblacklight/blacklight pull request #3270
Opened 2024-08-12 18:30 UTC by eliotjordan

Bump max Rails version to 7.2 in Blacklight 7.x to allow implementers time to upgrade from older versions of Rails that will be EOL soon.

2024-08-12 18:38 UTC, jcoyne requested changes

2024-08-12 18:38 UTC, jcoyne commented on .github/workflows/ruby.yml
> +      RAILS_VERSION: 7.1.3.4
Shouldn't this be 7.2.0?

2024-08-12 19:01 UTC, eliotjordan commented
@jcoyne Fixed.

2024-08-12 19:16 UTC, jcoyne commented on .github/workflows/ruby.yml
> +        ENGINE_CART_RAILS_OPTIONS: '--skip-spring --skip-keeps --skip-test'
```suggestion
        ENGINE_CART_RAILS_OPTIONS: '--skip-keeps --skip-test'
```

`--skip-spring ` is not an option in 7.2

2024-08-12 20:15 UTC, eliotjordan commented
@jcoyne This should be read to go.

2024-08-12 20:53 UTC, jcoyne commented
@eliotjordan it looks like we need to merge https://github.com/projectblacklight/blacklight/pull/3271 first.

2024-08-12 21:59 UTC, eliotjordan commented
@jcoyne Trey merged https://github.com/projectblacklight/blacklight/pull/3271. I rebased the changes into this branch.

2024-08-13 13:41 UTC, jcoyne approved these changes

2024-08-13 13:41 UTC, merged

2024-08-18 20:41 UTC, jrochkind commented
thank you!