update pagination to be links, moves next after numbers
projectblacklight/blacklight pull request #3272
Opened 2024-08-14 15:37 UTC by dnoneill

You can see the changes by changing https://github.com/projectblacklight/blacklight/blob/a8b5a3d3a2e8243c8a875d40528eae5c106d83bd/lib/blacklight/engine.rb#L71 to blacklight9

![Screenshot 2024-08-14 at 11 34 18 AM](https://github.com/user-attachments/assets/63345d4e-ffdf-48a1-b127-36da9b2c6cc9)

2024-08-14 16:02 UTC, jcoyne requested changes

2024-08-14 16:02 UTC, jcoyne commented on app/assets/stylesheets/blacklight/_pagination.scss
> +    color: black;
can we set `--bs-pagination-active-color` instead?  Is there a reason we need to customize this here and not in the host app?  The host app may make different choices for which colors are most appropriate.

2024-08-14 16:02 UTC, jcoyne commented on app/assets/stylesheets/blacklight/_pagination.scss
> +  .disabled a {
This rule should be unnecessary if you set `.page-item` on the node. https://getbootstrap.com/docs/5.3/components/pagination/#disabled-and-active-states

2024-08-14 16:02 UTC, jcoyne commented on app/assets/stylesheets/blacklight/_pagination.scss
> +  .btn {
I think we should avoid this class in favor of `.page-link`

2024-08-14 17:08 UTC, dnoneill commented on app/views/kaminari/blacklight9/_first_page.html.erb
> +  <%= link_to_unless current_page.first?, raw(t 'views.pagination.first'), url, :remote => remote, class: 'btn btn-link', aria: { label: t('views.pagination.aria.go_to_first_page') } %>
The page-link makes it look like a button, which we don't want. I didn't realize the page-link was part of a bootstrap configuration so it looks like I should remove the page-item class.

2024-08-14 18:06 UTC, dnoneill commented on app/views/kaminari/blacklight9/_prev_page.html.erb
> +      <%= link_to raw(t 'views.pagination.previous'), '#', :rel => 'prev', :onclick=>'return false;', class: 'btn btn-link text-decoration-none', aria: { label: t('views.pagination.aria.go_to_previou
That is what is in the current pagination.

2024-08-14 19:52 UTC, dnoneill commented on app/views/kaminari/blacklight9/_prev_page.html.erb
> +      <%= link_to raw(t 'views.pagination.previous'), url, :rel => 'prev', :remote => remote, class: 'btn btn-link text-decoration-none', aria: { label: t('views.pagination.aria.go_to_previous_page')
I don't know. This again was in the old code.

2024-09-18 13:32 UTC, jcoyne commented
@dnoneill this requires a rebase.

2024-09-25 12:54 UTC, merged